package com.kvajipertya.lessons.ui

object Strings {
    private val en = mapOf(
        "today_title" to "Today's Schedule",
        "no_subjects" to "No subjects scheduled for today!",
        "timetable_title" to "Timetable",
        "reminders_title" to "Reminders",
        "no_reminders" to "No reminders set.",
        "homework_title" to "Homework",
        "no_homework" to "No homework listed.",
        "subjects_today" to "Subjects for today",
        "settings_title" to "Settings",
        "appearance" to "Appearance",
        "theme" to "Theme",
        "auto" to "Auto",
        "light" to "Light",
        "dark" to "Dark",
        "follow_system" to "Follow System",
        "localization" to "Localization",
        "language" to "Language",
        "version" to "Version",
        "overdue" to "Overdue",
        "today" to "Today",
        "tomorrow" to "Tomorrow",
        "days_left" to "days left",
        "add_subject" to "Add Subject",
        "add_reminder" to "Add Reminder",
        "add_homework" to "Add Homework",
        "subject_name" to "Subject Name",
        "start_time" to "Start Time",
        "end_time" to "End Time",
        "task" to "Task",
        "due_date" to "Due Date",
        "ok" to "OK",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "nothing_planned" to "Nothing planned for today!",
        "active_lesson" to "Active Lesson",
        "next_lesson" to "Next Lesson",
        "school_over" to "School Over",
        "no_classes_today" to "No classes today.",
        "no_homework_today" to "No homework for today's subjects."
    )

    private val ka = mapOf(
        "today_title" to "დღევანდელი ცხრილი",
        "no_subjects" to "დღეს საგნები არ გაქვთ!",
        "timetable_title" to "ცხრილი",
        "reminders_title" to "შეხსენებები",
        "no_reminders" to "შეხსენებები არ არის.",
        "homework_title" to "დავალებები",
        "no_homework" to "დავალებები არ არის.",
        "subjects_today" to "დღევანდელი საგნები",
        "settings_title" to "პარამეტრები",
        "appearance" to "გარეგნობა",
        "theme" to "თემა",
        "auto" to "ავტო",
        "light" to "ნათელი",
        "dark" to "ბნელი",
        "follow_system" to "სისტემის მიხედვით",
        "localization" to "ლოკალიზაცია",
        "language" to "ენა",
        "version" to "ვერსია",
        "overdue" to "ვადაგადაცილებული",
        "today" to "დღეს",
        "tomorrow" to "ხვალ",
        "days_left" to "დღე დარჩა",
        "add_subject" to "საგნის დამატება",
        "add_reminder" to "შეხსენების დამატება",
        "add_homework" to "დავალების დამატება",
        "subject_name" to "საგნის სახელი",
        "start_time" to "დაწყება",
        "end_time" to "დასრულება",
        "task" to "დავალება",
        "due_date" to "ვადა",
        "ok" to "კარგი",
        "cancel" to "გაუქმება",
        "delete" to "წაშლა",
        "nothing_planned" to "დღეს არაფერია დაგეგმილი!",
        "active_lesson" to "მიმდინარე გაკვეთილი",
        "next_lesson" to "შემდეგი გაკვეთილი",
        "school_over" to "სკოლა დასრულდა",
        "no_classes_today" to "დღეს გაკვეთილები არ გაქვთ.",
        "no_homework_today" to "დღევანდელ საგნებზე დავალებები არ არის."
    )

    fun get(key: String, lang: String): String {
        val map = if (lang == "Georgian") ka else en
        return map[key] ?: en[key] ?: key
    }
}
